Bump version to 1.3.0, check tmp and src directorieis, fix libdir for 64 bits, fix exits

diff --git a/fltk.SlackBuild b/fltk.SlackBuild
--- a/fltk.SlackBuild
+++ b/fltk.SlackBuild
@@ -1,31 +1,67 @@
 #!/bin/sh
 #
-# SlackBuild for Fast Light Toolkit
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for Fast Light Toolkit
+# Copyright (C) 2007-2009,2011 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#
+# Visit SlackPack at http://sotirov-bg.net/slackpack/
+#
+# $Id: fltk.SlackBuild,v 1.5 2011/10/23 06:33:27 gsotirov Exp $
 #
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=fltk
-VERSION=1.1.10
-BUILD=1
+VERSION=1.3.0
+BUILD=${BUILD:-1}
 
 TMP=${TMP:-/tmp}
-CWD=${CWD:-`cwd`}
-PKG="$TMP/package-$NAME"
+CWD=${CWD:-`pwd`}
 
+if [ ! -e $TMP ]; then
+  mkdir -p $TMP # location to build the source
+fi
+
+SRC=$TMP/$NAME-$VERSION
+if [ -e $SRC -a -d $SRC ]; then
+  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  exit 1
+fi
+
+PKG=$TMP/package-$NAME
+if [ -e $PKG -a -d $PKG ]; then
+  echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
+  exit 2
+fi
+mkdir -p $PKG
+
+# Extract the source
 cd $TMP
-tar -jxvf $CWD/${NAME}-${VERSION}-source.tar.bz2
-SRC=$TMP/${NAME}-${VERSION}
+tar -xvf $CWD/${NAME}-${VERSION}-source.tar.?z* || exit 3
 cd $SRC
 fix_source
 
+# Configure
 CFLAGS=$SLKCFLAGS \
 CXXFLAGS=$SLKCFLAGS \
 ./configure --build=$ARCH-slackware-linux \
             --host=$ARCH-slackware-linux \
             --prefix=/usr \
             --sysconfdir=/etc \
+            --libdir=/usr/lib${LIBDIRSUFFIX} \
             --mandir=/usr/man \
             --enable-static=no \
             --enable-shared=yes \
@@ -33,12 +69,14 @@ CXXFLAGS=$SLKCFLAGS \
             --enable-threads \
             --enable-largefile \
             --enable-xinerama \
-            --enable-xft || exit 1
+            --enable-xft \
+	    --enable-xdbe || exit 4
 
-make -j4 || exit 2
+# Build & install
+make -j4 || exit 5
+make DESTDIR=$PKG install || exit 6
 
-make DESTDIR=$PKG install || exit 3
-
+# Prepare
 bin_perms $PKG
 ( cd $PKG; strip_bin; strip_lib )
 ( cd $SRC; create_docs $PKG $NAME-$VERSION )
@@ -54,6 +92,7 @@ install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION
 install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION
 
+# Pack
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -61,6 +100,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
